---
# LimitRange for Team Beta namespace (Higher limits for data processing)
apiVersion: v1
kind: LimitRange
metadata:
  name: team-beta-limits
  namespace: team-beta
  labels:
    team: beta
spec:
  limits:
    # Container limits
    - type: Container
      max:
        cpu: "8"
        memory: "16Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"
      maxLimitRequestRatio:
        cpu: "4"
        memory: "4"

    # Pod limits
    - type: Pod
      max:
        cpu: "16"
        memory: "32Gi"
      min:
        cpu: "200m"
        memory: "256Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "200Gi"
      min:
        storage: "1Gi"
