---
# LimitRange for Team Gamma namespace (Lower limits for staging)
apiVersion: v1
kind: LimitRange
metadata:
  name: team-gamma-limits
  namespace: team-gamma
  labels:
    team: gamma
spec:
  limits:
    # Container limits
    - type: Container
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      maxLimitRequestRatio:
        cpu: "4"
        memory: "4"

    # Pod limits
    - type: Pod
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "50Gi"
      min:
        storage: "1Gi"
