---
# LimitRange for Team Alpha namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: team-alpha-limits
  namespace: team-alpha
  labels:
    team: alpha
spec:
  limits:
    # Container limits
    - type: Container
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      maxLimitRequestRatio:
        cpu: "4"
        memory: "4"

    # Pod limits
    - type: Pod
      max:
        cpu: "8"
        memory: "16Gi"
      min:
        cpu: "200m"
        memory: "256Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "100Gi"
      min:
        storage: "1Gi"
