---
# Bind platform admin ClusterRole to platform admin service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-admin-binding
  labels:
    app: platform
subjects:
  - kind: ServiceAccount
    name: platform-admin
    namespace: platform
roleRef:
  kind: ClusterRole
  name: platform-admin
  apiGroup: rbac.authorization.k8s.io
