apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    team: platform
    environment: shared
    managed-by: platform-team
  annotations:
    description: "Platform namespace for shared services and monitoring tools"
    owner: "platform-team@company.com"
    cost-center: "CC-PLATFORM-000"
