apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    name: team-alpha
    team: alpha
    environment: production
    managed-by: platform-team
  annotations:
    description: "Production namespace for Team Alpha - handles customer-facing services"
    owner: "alpha-team-lead@company.com"
    cost-center: "CC-ALPHA-001"
