apiVersion: v1
kind: Namespace
metadata:
  name: team-beta
  labels:
    name: team-beta
    team: beta
    environment: production
    managed-by: platform-team
  annotations:
    description: "Production namespace for Team Beta - handles data processing services"
    owner: "beta-team-lead@company.com"
    cost-center: "CC-BETA-002"
